name: job-orchestra
channels:
  - conda-forge
  - anaconda
  - conda
  - defaults
dependencies:
  - python>=3.11
  - python-fastjsonschema   # == fastjsonschema if using pip
  - pyarrow>=17.0.0
  - cleverdict>=1.9.2
  - pathvalidate
  - pytest
  - flatdict>=4.0.1
  - poetry
  - pip
  - pip:
    - dagviz>=0.4.0